ACM:
    device: cuda
    logger:
        name: ACM
        mode: both
        dir: ./log/ACM/
    dataset:
        dir: ../data/ACM/
        augmentation:
            add_self_loops: false
            drop_edge: 0.0
            drop_feature: 0.0
            add_edge: 0.0
            add_noise: 0.0
            pca_dim: 100
    model:
        dims:
            ae: [ 128, 256, 512, 20 ]
            igae: [ 128, 256, 20]
        v: 1.0
    train:
        pretrain:
            ae:
                dir: ./pretrain/ACM/
                max_epoch: 30
                lr: 1e-3
            igae:
                dir: ./pretrain/ACM/
                max_epoch: 30
                lr: 1e-3
                gamma_value: 0.1
            both:
                dir: ./pretrain/ACM/
                max_epoch: 100
                lr: 1e-3
                alpha: 0.1
                beta: 0.01
                omega: 0.1
        seed: 1
        rounds: 1
        max_epoch: 50
        lr: 5e-5
        gamma_value: 0.1
        lambda_value: 10
    visualize:
        tsne: true
        umap: false
        heatmap: false
        loss: true
        dir: ./visualization/ACM/
        when: end
    evaluate:
        each: true
        acc: true
        nmi: true
        ari: true
        f1: true
        hom: true
        com: true
        pur: true
        sc: true
        gre: true
