ACM:
    device: cuda
    logger:
        name: ACM
        mode: both
        dir: ./log/ACM/
    dataset:
        dir: ../data/ACM/
        augmentation:
            add_self_loops: true
            drop_edge: 0.0
            drop_feature: 0.0
            add_edge: 0.0
            add_noise: 0.0
            pca_dim: 50
    model:
        dims: [1000, 500, 500, 500]
    train:
        seed: 0
        rounds: 1
        max_epoch: 200
        lr: 5e-4
        view_lr: 1e-4
        reg_lambda: 1
    visualize:
        tsne: true
        umap: false
        heatmap: false
        loss: true
        dir: ./visualization/ACM/
        when: end
    evaluate:
        each: true
        acc: true
        nmi: true
        ari: true
        f1: true
        hom: true
        com: true
        pur: true
        sc: true
        gre: true
CITE:
    device: cuda
    logger:
        name: CITE
        mode: both
        dir: ./log/CITE/
    dataset:
        dir: ../data/CITE/
        augmentation:
            add_self_loops: true
            drop_edge: 0.0
            drop_feature: 0.0
            add_edge: 0.0
            add_noise: 0.0
    model:
        dims: [ 500, 500, 2000, 10 ]
        act: relu
        act_last: false
    train:
        pretrain:
            seed: -1
            rounds: 1
            dir: ./pretrain/CITE/
            max_epoch: 30
            lr: 1e-3
        seed: -1
        rounds: 10
        max_epoch: 50
        lr: 1e-4
        alpha: 0.1
        beta: 0.01
        sigma: 0.5
    visualize:
        tsne: true
        umap: false
        heatmap: false
        loss: true
        dir: ./visualization/CITE/
        when: end
    evaluate:
        each: true
        acc: true
        nmi: true
        ari: true
        f1: true
        hom: true
        com: true
        pur: true
CORA:
    device: cuda
    logger:
        name: CORA
        mode: both
        dir: ./log/CORA/
    dataset:
        dir: ../data/CORA/
        augmentation:
            add_self_loops: true
            drop_edge: 0.0
            drop_feature: 0.0
            add_edge: 0.0
            add_noise: 0.0
    model:
        dims: [ 500, 500, 2000, 10 ]
        act: relu
        act_last: false
    train:
        pretrain:
            seed: 0
            rounds: 1
            dir: ./pretrain/CORA/
            max_epoch: 30
            lr: 1e-3
        seed: -1
        rounds: 10
        max_epoch: 50
        lr: 1e-3
        alpha: 0.1
        beta: 0.01
        sigma: 0.5
    visualize:
        tsne: true
        umap: false
        heatmap: false
        loss: true
        dir: ./visualization/CORA/
        when: end
    evaluate:
        each: true
        acc: true
        nmi: true
        ari: true
        f1: true
        hom: true
        com: true
        pur: true
DBLP:
    device: cuda
    logger:
        name: DBLP
        mode: both
        dir: ./log/DBLP/
    dataset:
        dir: ../data/DBLP/
        augmentation:
            add_self_loops: true
            drop_edge: 0.0
            drop_feature: 0.0
            add_edge: 0.0
            add_noise: 0.0
    model:
        dims: [ 500, 500, 2000, 10 ]
        act: relu
        act_last: false
    train:
        pretrain:
            seed: 325
            rounds: 1
            dir: ./pretrain/DBLP/
            max_epoch: 30
            lr: 1e-3
        seed: -1
        rounds: 10
        max_epoch: 50
        lr: 1e-3
        alpha: 0.1
        beta: 0.01
        sigma: 0.5
    visualize:
        tsne: true
        umap: false
        heatmap: false
        loss: true
        dir: ./visualization/DBLP/
        when: end
    evaluate:
        each: true
        acc: true
        nmi: true
        ari: true
        f1: true
        hom: true
        com: true
        pur: true